# Generated by Django 4.2.3 on 2023-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='uuid'),
        ),
    ]
